# Generated by Django 3.2.9 on 2021-11-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveequityresult',
            name='difference',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='liveequityresult',
            name='section',
            field=models.IntegerField(default=0),
        ),
    ]
