# Generated by Django 3.1.6 on 2021-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210920_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveoitotal',
            name='strikegap',
            field=models.CharField(default='', max_length=20),
        ),
    ]
