# Generated by Django 3.2.9 on 2021-11-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211102_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveequityresult',
            name='change_perc',
            field=models.FloatField(default=0),
        ),
    ]
