# Generated by Django 3.1.6 on 2021-09-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_liveoitotal_strikegap'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveequityresult',
            name='opencrossed',
            field=models.CharField(default='', max_length=20),
        ),
    ]
