# Generated by Django 3.1.6 on 2021-09-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_livesegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='gainloss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('segment', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
