# Generated by Django 3.1.6 on 2021-09-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_gainloss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gainloss',
        ),
        migrations.AlterField(
            model_name='livesegment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
