# Generated by Django 3.1.6 on 2021-10-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211001_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesegment',
            name='change_perc',
            field=models.FloatField(default=0),
        ),
    ]
