# Generated by Django 3.2.8 on 2021-10-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_testequityresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesegment',
            name='doneToday',
            field=models.CharField(default='', max_length=10),
        ),
    ]
